### ISSUE TITLE
Optimize crafting menu UI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Wolfgange3311999/Port-Craft#10]
```
-only show/show first the crafting recipes that the player has items for
-subcategorize items (perhaps with buttons for each category)
```

Original issue reported on code.google.com by `Matthew3...@gmail.com` on 16 Dec 2014 at 2:17

**Comment by Wolfgange3311999** [comment]
The only thing left is to sub categorize items. (The other is already implemented)

**Comment by Wolfgange3311999** [comment]
For the release, sub-categorization isn't necessary. And that should be an option rather than replacing the current setup.
