### ISSUE TITLE
Create actual README

### ISSUE THREAD

**Issue by Wolfgange3311999** [Wolfgange3311999/Port-Craft#70]
This should have a screenshot, and maybe some build instructions.

**Comment by Ajusa** [comment]
Build instructions please! 
I would love to help out. My C++ knowledge is pretty basic, but this looks like it would be a great opportunity to learn :D

**Comment by Wolfgange3311999** [comment]
Ok, I've just finished adding some build instructions. Let me know if you run into any issues.
